### PR TITLE
Added filters to login and registration redirect  URLs

### PR DESCRIPTION
**Pull request by w3guy**
@tungnx89 @daonham @tuanta88 Please review and merge. 

These filters will be important for us.

### CODE REVIEW

**Comment by tungnxt89** [comment]
Hi w3guy,

We added 2 hooks "learn-press/register-redirect" and "learn-press/login-redirect" on branch "addons". You can see [dd433f1c](https://github.com/LearnPress/learnpress/commit/dd433f1cf2551d47cbf75f6a451cf1ba6cbc8abe) and [f05eafb](https://github.com/LearnPress/learnpress/commit/f05eafbd57f35017497268befd8d73f72e8968f1)

Please test and feedback.

Thanks.

**Comment by w3guy** [comment]
@tungnxt89 I'll test and get back to you.

**Comment by w3guy** [comment]
Any idea when this will be included in a future plugin update?

**Comment by tungnxt89** [comment]
> Any idea when this will be included in a future plugin update?

Hi w3guy,

We added it on LP v4.2.1 released https://vi.wordpress.org/plugins/learnpress/#developers.

Thanks.

**Comment by w3guy** [comment]
Thank you.

**Pull request closed without merging**
